// ─── PACE4 EXERCISE DATABASE ──────────────────────────────────────────────
// cat: Strength | Conditioning | Skills | Mobility
// fieldType: strength | reps_only | cardio_run | cardio_machine | cardio_cycle | timed | sport

export const ALL_EXERCISES = [

  // ── STRENGTH · Chest ──
  { "name": "Flat Barbell Bench Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Incline Barbell Bench Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Decline Barbell Bench Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Smith Machine Bench Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Machine Chest Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Dumbbell Flat Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Incline Dumbbell Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Decline Dumbbell Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Kettlebell Floor Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Cable Chest Fly", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Incline Cable Fly", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Decline Cable Fly", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Pec Deck Machine", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Dumbbell Chest Fly", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Wide Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Diamond Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Archer Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Decline Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Incline Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Pike Push Up", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Chest Dip", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Svend Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Single Arm Dumbbell Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Landmine Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },
  { "name": "Guillotine Press", "cat": "Strength", "sub": "Chest", "fieldType": "strength" },

  // ── STRENGTH · Back ──
  { "name": "Deadlift", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Romanian Deadlift", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Sumo Deadlift", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Trap Bar Deadlift", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Stiff Leg Deadlift", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Barbell Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Pendlay Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Dumbbell Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Single Arm Dumbbell Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Chest Supported Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "T-Bar Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Cable Row (Seated)", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Cable Row (Standing)", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Face Pull", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Pull Up", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Chin Up", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Neutral Grip Pull Up", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Wide Grip Pull Up", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Weighted Pull Up", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Lat Pulldown", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Close Grip Lat Pulldown", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Single Arm Lat Pulldown", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Straight Arm Pulldown", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Reverse Fly", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Shrug", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Rack Pull", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Good Morning", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Hyperextension", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Reverse Hyperextension", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Meadows Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },
  { "name": "Kroc Row", "cat": "Strength", "sub": "Back", "fieldType": "strength" },

  // ── STRENGTH · Shoulders ──
  { "name": "Overhead Press (Barbell)", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Seated Dumbbell Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Arnold Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Machine Shoulder Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Smith Machine Overhead Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Lateral Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Cable Lateral Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Front Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Rear Delt Fly", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Rear Delt Machine", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Cable Rear Delt Fly", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Upright Row", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Landmine Lateral Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Landmine Press (Shoulder)", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Single Arm Cable Front Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Face Pull (Shoulders)", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Bus Driver", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Plate Front Raise", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Band Pull Apart", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Cuban Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Bradford Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },
  { "name": "Push Press", "cat": "Strength", "sub": "Shoulders", "fieldType": "strength" },

  // ── STRENGTH · Arms ──
  { "name": "Barbell Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Dumbbell Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Hammer Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Incline Dumbbell Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Preacher Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Concentration Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Cable Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "EZ Bar Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Spider Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Zottman Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "21s Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Reverse Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Wrist Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Reverse Wrist Curl", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Close Grip Bench Press", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Skull Crusher", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Tricep Dip", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Overhead Tricep Extension", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Cable Tricep Pushdown", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Rope Pushdown", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Single Arm Pushdown", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Kickback", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Diamond Push Up (Triceps)", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "JM Press", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Tate Press", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },
  { "name": "Tricep Machine", "cat": "Strength", "sub": "Arms", "fieldType": "strength" },

  // ── STRENGTH · Legs ──
  { "name": "Back Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Front Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Goblet Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Sumo Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Box Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Hack Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Bulgarian Split Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Leg Press", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Lunge", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Walking Lunge", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Reverse Lunge", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Lateral Lunge", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Step Up", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Romanian Deadlift (Legs)", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Leg Extension", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Leg Curl", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Seated Leg Curl", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Nordic Curl", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Glute Ham Raise", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Hip Thrust", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Glute Bridge", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Cable Kickback", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Donkey Kick", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Fire Hydrant", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Wall Sit", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Pistol Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Calf Raise (Standing)", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Calf Raise (Seated)", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Single Leg Calf Raise", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Leg Abduction Machine", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Leg Adduction Machine", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Sissy Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Jefferson Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Zercher Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Safety Bar Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Pause Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },
  { "name": "Tempo Squat", "cat": "Strength", "sub": "Legs", "fieldType": "strength" },

  // ── STRENGTH · Core ──
  { "name": "Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Reverse Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Bicycle Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Cable Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Decline Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Sit Up", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "V-Up", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Tuck Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Russian Twist", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Weighted Russian Twist", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Medicine Ball Russian Twist", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Plank", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Side Plank", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Side Plank with Hip Dip", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Weighted Plank", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Plank with Shoulder Tap", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Plank Up Downs", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Hollow Hold", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Hollow Body Rock", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "L-Sit", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Dead Bug", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Pallof Press", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Ab Wheel Rollout", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Barbell Rollout", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Dragon Flag", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Leg Raise", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Hanging Leg Raise", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Hanging Knee Raise", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Toe to Bar", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Windshield Wiper", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Wood Chop", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Cable Wood Chop", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Landmine Rotation", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Suitcase Carry", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Farmer's Walk", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Copenhagen Plank", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Bear Crawl", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Bird Dog", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Mountain Climber", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Flutter Kicks", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Scissor Kicks", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Heel Touch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Jackknife Sit Up", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Plank Jack", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Spiderman Plank", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Stir the Pot", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Stability Ball Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Stability Ball Rollout", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Bosu Ball Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "TRX Pike", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "TRX Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Ab Coaster", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Abs Machine Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Oblique Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Twisting Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },
  { "name": "Long Arm Crunch", "cat": "Strength", "sub": "Core", "fieldType": "strength" },

  // ── STRENGTH · Glutes ──
  { "name": "Hip Thrust (Barbell)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Hip Thrust (Dumbbell)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Hip Thrust (Machine)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Cable Pull Through", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "45° Back Extension", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Single Leg Hip Thrust", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Frog Pump", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Banded Hip Thrust", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Sumo Deadlift (Glutes)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Cable Kickback (Glutes)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },
  { "name": "Step Up (Glutes)", "cat": "Strength", "sub": "Glutes", "fieldType": "strength" },

  // ── CONDITIONING · Cardio Machine ──
  { "name": "Rowing Ergometer", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "SkiErg", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Assault Bike", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Echo Bike", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Air Runner", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Sled Push", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Sled Pull", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Battle Ropes", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "VO2 Max Test", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_machine" },
  { "name": "Treadmill Run", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_run" },
  { "name": "Elliptical", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_run" },
  { "name": "Stationary Bike", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_run" },
  { "name": "Spin Bike", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_run" },
  { "name": "Stair Climber", "cat": "Conditioning", "sub": "Cardio Machine", "fieldType": "cardio_run" },

  // ── CONDITIONING · Running ──
  { "name": "Easy Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Tempo Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Interval Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Fartlek Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Long Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "5K Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "10K Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Half Marathon Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Marathon Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Sprint", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Hill Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Track Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Trail Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Recovery Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Strides", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Progression Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Negative Split Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },
  { "name": "Lactate Threshold Run", "cat": "Conditioning", "sub": "Running", "fieldType": "cardio_run" },

  // ── CONDITIONING · HIIT ──
  { "name": "Burpee", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Box Jump", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Jump Squat", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Tuck Jump", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Broad Jump", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Lateral Bound", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Depth Jump", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Jump Lunge", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Mountain Climber", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "High Knees", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Jump Rope", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Double Under", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Tabata Circuit", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "AMRAP Circuit", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "EMOM Circuit", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Kettlebell Swing", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Kettlebell Snatch", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Kettlebell Clean", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Kettlebell Turkish Get Up", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Medicine Ball Slam", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Wall Ball", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Sandbag Carry", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Tire Flip", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Farmer Carry", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Dumbbell Snatch", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Thruster", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Clean and Press", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },
  { "name": "Hang Power Clean", "cat": "Conditioning", "sub": "HIIT", "fieldType": "reps_only" },

  // ── CONDITIONING · Cycling ──
  { "name": "Outdoor Cycling", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Road Cycling", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Mountain Biking", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Cycling Interval", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Cycling Endurance Ride", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Cycling Sprint", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },
  { "name": "Gravel Riding", "cat": "Conditioning", "sub": "Cycling", "fieldType": "cardio_cycle" },

  // ── CONDITIONING · Swimming ──
  { "name": "Freestyle Swim", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Breaststroke", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Backstroke", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Butterfly", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Open Water Swim", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Swim Interval", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Swim Endurance", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Kickboard Drill", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },
  { "name": "Pull Buoy Drill", "cat": "Conditioning", "sub": "Swimming", "fieldType": "timed" },

  // ── SKILLS · Hyrox ──
  { "name": "SkiErg (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Sled Push (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Sled Pull (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Burpee Broad Jump", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Rowing (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Farmers Carry (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Sandbag Lunges", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Wall Ball (Hyrox)", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Hyrox Full Simulation", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },
  { "name": "Hyrox Race Practice", "cat": "Skills", "sub": "Hyrox", "fieldType": "cardio_machine" },

  // ── SKILLS · CrossFit ──
  { "name": "Power Clean", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Hang Power Clean", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Power Snatch", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Hang Power Snatch", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Clean & Jerk", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Squat Clean", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Split Jerk", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Push Jerk", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Overhead Squat", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Snatch Balance", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Muscle Up (Bar)", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Muscle Up (Ring)", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Kipping Pull Up", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Butterfly Pull Up", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Handstand Push Up", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Handstand Walk", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Ring Dip", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Ring Row", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Rope Climb", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Toes to Bar", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Double Under", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "WOD (Custom)", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Fran", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Cindy", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },
  { "name": "Murph", "cat": "Skills", "sub": "CrossFit", "fieldType": "reps_only" },

  // ── SKILLS · Combat Sports ──
  { "name": "Boxing Sparring", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Shadow Boxing", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Heavy Bag Work", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Pad Work", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Speed Bag", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Wrestling Drilling", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Jiu Jitsu Rolling", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "MMA Sparring", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Muay Thai Clinch", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Kickboxing Drill", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Karate Kata", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Judo Randori", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },
  { "name": "Wrestling Live Round", "cat": "Skills", "sub": "Combat Sports", "fieldType": "timed" },

  // ── SKILLS · Team Sports ──
  { "name": "Football Practice", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Cricket Nets", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Basketball Scrimmage", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Volleyball Match", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Hockey Practice", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Tennis Drill", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Badminton Game", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Table Tennis", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Swimming Race", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Rugby Practice", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Kabaddi Practice", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Kho Kho", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },
  { "name": "Athletics Drill", "cat": "Skills", "sub": "Team Sports", "fieldType": "sport" },

  // ── SKILLS · Calisthenics ──
  { "name": "Front Lever", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Back Lever", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Planche", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Human Flag", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Iron Cross", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Handstand (Freestanding)", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Handstand Push Up (Wall)", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Pistol Squat (Weighted)", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "One Arm Push Up", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "One Arm Pull Up", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Ring Support Hold", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "L-Sit (Rings)", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "V-Sit", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Press to Handstand", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Wall Walk", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },
  { "name": "Skin the Cat", "cat": "Skills", "sub": "Calisthenics", "fieldType": "timed" },

  // ── MOBILITY · Stretching ──
  { "name": "Hip Flexor Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Quad Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Hamstring Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Pigeon Pose", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Figure Four Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Glute Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "IT Band Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Calf Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Chest Stretch (Doorway)", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Pec Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Lat Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Thoracic Rotation", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Child's Pose", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Downward Dog", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Upward Dog", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Cat Cow", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Cobra Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Neck Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Shoulder Cross Body Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Tricep Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Wrist Circles", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Ankle Circles", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Seated Forward Fold", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Standing Forward Fold", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Butterfly Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Frog Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "90-90 Hip Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Couch Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },
  { "name": "Wall Chest Stretch", "cat": "Mobility", "sub": "Stretching", "fieldType": "timed" },

  // ── MOBILITY · Yoga ──
  { "name": "Sun Salutation", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Warrior I", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Warrior II", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Warrior III", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Triangle Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Tree Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Chair Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Eagle Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Lizard Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Low Lunge", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Crescent Lunge", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Half Moon", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Boat Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Bridge Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Wheel Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Shoulder Stand", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Headstand", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Crow Pose", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Yoga Flow (30 min)", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Yin Yoga", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Power Yoga", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Ashtanga", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Vinyasa", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Pranayama", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },
  { "name": "Meditation", "cat": "Mobility", "sub": "Yoga", "fieldType": "timed" },

  // ── MOBILITY · Recovery ──
  { "name": "Foam Roll Quads", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Hamstrings", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll IT Band", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Glutes", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Upper Back", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Lats", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Calves", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Foam Roll Hip Flexors", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Lacrosse Ball Chest", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Lacrosse Ball Glutes", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Lacrosse Ball Feet", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "PNF Stretching", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Active Release", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Contrast Shower", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Ice Bath", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Sauna Session", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Massage Gun Quads", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Massage Gun Back", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Full Body Foam Roll", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },
  { "name": "Mobility Flow", "cat": "Mobility", "sub": "Recovery", "fieldType": "timed" },

  // ── MOBILITY · Warm Up ──
  { "name": "Jumping Jacks", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Arm Circles", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Hip Circles", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Leg Swings", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Inchworm", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "World's Greatest Stretch", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Walking Knee Hug", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Walking Quad Pull", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Butt Kicks", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "High Knees (Warmup)", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Lateral Shuffle", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Carioca", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "A-Skip", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "B-Skip", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Glute Bridge Activation", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Clamshell", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Monster Walk", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Band Walk (Lateral)", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Shoulder Dislocates", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Thoracic Extension on Foam Roller", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
  { "name": "Spiderman Stretch", "cat": "Mobility", "sub": "Warm Up", "fieldType": "timed" },
]