// ─── PACE4 EXERCISE DATABASE ──────────────────────────────────────
// Edit this file to add, remove or update exercises
// Format: { name, cat, sub }
// cat: 'Strength' | 'Conditioning' | 'Skills' | 'Mobility' | 'Custom'
// sub: subcategory label shown in search results

export const ALL_EXERCISES = [
  // STRENGTH — Chest
  { name: 'Flat Bench Press', cat: 'Strength', sub: 'Chest' },
  { name: 'Incline Bench Press', cat: 'Strength', sub: 'Chest' },
  { name: 'Decline Bench Press', cat: 'Strength', sub: 'Chest' },
  { name: 'Dumbbell Chest Press', cat: 'Strength', sub: 'Chest' },
  { name: 'Incline Dumbbell Press', cat: 'Strength', sub: 'Chest' },
  { name: 'Chest Flyes', cat: 'Strength', sub: 'Chest' },
  { name: 'Cable Crossover', cat: 'Strength', sub: 'Chest' },
  { name: 'Pec Deck', cat: 'Strength', sub: 'Chest' },
  { name: 'Push Ups', cat: 'Strength', sub: 'Chest' },
  { name: 'Dips', cat: 'Strength', sub: 'Chest' },
  // STRENGTH — Back
  { name: 'Deadlift', cat: 'Strength', sub: 'Back' },
  { name: 'Barbell Row', cat: 'Strength', sub: 'Back' },
  { name: 'Dumbbell Row', cat: 'Strength', sub: 'Back' },
  { name: 'Lat Pulldown', cat: 'Strength', sub: 'Back' },
  { name: 'Seated Cable Row', cat: 'Strength', sub: 'Back' },
  { name: 'T-Bar Row', cat: 'Strength', sub: 'Back' },
  { name: 'Face Pulls', cat: 'Strength', sub: 'Back' },
  { name: 'Pull Ups', cat: 'Strength', sub: 'Back' },
  { name: 'Chin Ups', cat: 'Strength', sub: 'Back' },
  { name: 'Rack Pull', cat: 'Strength', sub: 'Back' },
  // STRENGTH — Shoulders
  { name: 'Overhead Press', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Dumbbell Shoulder Press', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Arnold Press', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Lateral Raises', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Front Raises', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Rear Delt Flyes', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Shrugs', cat: 'Strength', sub: 'Shoulders' },
  { name: 'Upright Row', cat: 'Strength', sub: 'Shoulders' },
  // STRENGTH — Legs
  { name: 'Barbell Squat', cat: 'Strength', sub: 'Legs' },
  { name: 'Front Squat', cat: 'Strength', sub: 'Legs' },
  { name: 'Leg Press', cat: 'Strength', sub: 'Legs' },
  { name: 'Romanian Deadlift', cat: 'Strength', sub: 'Legs' },
  { name: 'Leg Curl', cat: 'Strength', sub: 'Legs' },
  { name: 'Leg Extension', cat: 'Strength', sub: 'Legs' },
  { name: 'Bulgarian Split Squat', cat: 'Strength', sub: 'Legs' },
  { name: 'Lunges', cat: 'Strength', sub: 'Legs' },
  { name: 'Hack Squat', cat: 'Strength', sub: 'Legs' },
  { name: 'Calf Raises', cat: 'Strength', sub: 'Legs' },
  { name: 'Hip Thrust', cat: 'Strength', sub: 'Legs' },
  { name: 'Glute Bridge', cat: 'Strength', sub: 'Legs' },
  // STRENGTH — Arms
  { name: 'Barbell Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Dumbbell Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Hammer Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Preacher Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Cable Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Concentration Curl', cat: 'Strength', sub: 'Arms' },
  { name: 'Tricep Pushdown', cat: 'Strength', sub: 'Arms' },
  { name: 'Skull Crushers', cat: 'Strength', sub: 'Arms' },
  { name: 'Overhead Tricep Extension', cat: 'Strength', sub: 'Arms' },
  { name: 'Close Grip Bench', cat: 'Strength', sub: 'Arms' },
  // STRENGTH — Power
  { name: 'Power Clean', cat: 'Strength', sub: 'Power' },
  { name: 'Clean & Jerk', cat: 'Strength', sub: 'Power' },
  { name: 'Snatch', cat: 'Strength', sub: 'Power' },
  { name: 'Hang Clean', cat: 'Strength', sub: 'Power' },
  { name: 'Push Press', cat: 'Strength', sub: 'Power' },
  { name: 'Thruster', cat: 'Strength', sub: 'Power' },
  { name: 'Farmers Walk', cat: 'Strength', sub: 'Power' },
  { name: 'Kettlebell Swing', cat: 'Strength', sub: 'Power' },
  { name: 'Turkish Get Up', cat: 'Strength', sub: 'Power' },
  { name: 'Sled Push', cat: 'Strength', sub: 'Power' },
  { name: 'Sled Pull', cat: 'Strength', sub: 'Power' },
  { name: 'Muscle Ups', cat: 'Strength', sub: 'Power' },
  { name: 'Handstand Push Ups', cat: 'Strength', sub: 'Power' },
  // CONDITIONING — Running
  { name: 'Easy Run', cat: 'Conditioning', sub: 'Running' },
  { name: 'Tempo Run', cat: 'Conditioning', sub: 'Running' },
  { name: 'Long Run', cat: 'Conditioning', sub: 'Running' },
  { name: 'Interval Run', cat: 'Conditioning', sub: 'Running' },
  { name: 'Hill Run', cat: 'Conditioning', sub: 'Running' },
  { name: 'Sprint Session', cat: 'Conditioning', sub: 'Running' },
  { name: 'Fartlek', cat: 'Conditioning', sub: 'Running' },
  { name: 'Recovery Jog', cat: 'Conditioning', sub: 'Running' },
  // CONDITIONING — Machine
  { name: 'Row Erg', cat: 'Conditioning', sub: 'Machine' },
  { name: 'SkiErg', cat: 'Conditioning', sub: 'Machine' },
  { name: 'Assault Bike', cat: 'Conditioning', sub: 'Machine' },
  { name: 'Stairmaster', cat: 'Conditioning', sub: 'Machine' },
  { name: 'Elliptical', cat: 'Conditioning', sub: 'Machine' },
  { name: 'Treadmill', cat: 'Conditioning', sub: 'Machine' },
  // CONDITIONING — Cycling
  { name: 'Steady State Ride', cat: 'Conditioning', sub: 'Cycling' },
  { name: 'Interval Ride', cat: 'Conditioning', sub: 'Cycling' },
  { name: 'Indoor Cycling', cat: 'Conditioning', sub: 'Cycling' },
  // CONDITIONING — HIIT
  { name: 'Burpees', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'Box Jumps', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'Jump Rope', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'Battle Ropes', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'Mountain Climbers', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'Tabata', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'AMRAP', cat: 'Conditioning', sub: 'HIIT' },
  { name: 'EMOM', cat: 'Conditioning', sub: 'HIIT' },
  // CONDITIONING — Core
  { name: 'Plank', cat: 'Conditioning', sub: 'Core' },
  { name: 'Side Plank', cat: 'Conditioning', sub: 'Core' },
  { name: 'Hollow Hold', cat: 'Conditioning', sub: 'Core' },
  { name: 'L-Sit', cat: 'Conditioning', sub: 'Core' },
  { name: 'Crunches', cat: 'Conditioning', sub: 'Core' },
  { name: 'Bicycle Crunches', cat: 'Conditioning', sub: 'Core' },
  { name: 'Leg Raises', cat: 'Conditioning', sub: 'Core' },
  { name: 'Hanging Leg Raises', cat: 'Conditioning', sub: 'Core' },
  { name: 'Ab Wheel Rollout', cat: 'Conditioning', sub: 'Core' },
  { name: 'Russian Twist', cat: 'Conditioning', sub: 'Core' },
  { name: 'Dragon Flag', cat: 'Conditioning', sub: 'Core' },
  { name: 'V Ups', cat: 'Conditioning', sub: 'Core' },
  { name: 'Dead Bug', cat: 'Conditioning', sub: 'Core' },
  // SKILLS
  { name: 'Football Drills', cat: 'Skills', sub: 'Team Sports' },
  { name: 'Cricket Batting', cat: 'Skills', sub: 'Team Sports' },
  { name: 'Cricket Bowling', cat: 'Skills', sub: 'Team Sports' },
  { name: 'Basketball Drills', cat: 'Skills', sub: 'Team Sports' },
  { name: 'Volleyball Practice', cat: 'Skills', sub: 'Team Sports' },
  { name: 'Tennis Drills', cat: 'Skills', sub: 'Racket' },
  { name: 'Badminton Practice', cat: 'Skills', sub: 'Racket' },
  { name: 'Squash', cat: 'Skills', sub: 'Racket' },
  { name: 'Boxing Sparring', cat: 'Skills', sub: 'Combat' },
  { name: 'MMA Sparring', cat: 'Skills', sub: 'Combat' },
  { name: 'Kickboxing', cat: 'Skills', sub: 'Combat' },
  { name: 'Muay Thai', cat: 'Skills', sub: 'Combat' },
  { name: 'Wrestling', cat: 'Skills', sub: 'Combat' },
  { name: 'BJJ Rolling', cat: 'Skills', sub: 'Combat' },
  { name: 'Pad Work', cat: 'Skills', sub: 'Combat' },
  { name: 'Heavy Bag', cat: 'Skills', sub: 'Combat' },
  { name: 'Gymnastics Practice', cat: 'Skills', sub: 'Movement' },
  { name: 'Parkour', cat: 'Skills', sub: 'Movement' },
  { name: 'Breakdancing', cat: 'Skills', sub: 'Movement' },
  { name: 'Freestyle Movement', cat: 'Skills', sub: 'Movement' },
  { name: 'Handstand Practice', cat: 'Skills', sub: 'Movement' },
  { name: 'Climbing', cat: 'Skills', sub: 'Movement' },
  { name: 'Dance Practice', cat: 'Skills', sub: 'Movement' },
  { name: 'Sport Practice', cat: 'Skills', sub: 'General' },
  { name: 'Scrimmage', cat: 'Skills', sub: 'General' },
  // MOBILITY
  { name: 'Sun Salutation', cat: 'Mobility', sub: 'Yoga' },
  { name: 'Yoga Flow', cat: 'Mobility', sub: 'Yoga' },
  { name: 'Yin Yoga', cat: 'Mobility', sub: 'Yoga' },
  { name: 'Hot Yoga', cat: 'Mobility', sub: 'Yoga' },
  { name: 'Power Yoga', cat: 'Mobility', sub: 'Yoga' },
  { name: 'Hip Flexor Stretch', cat: 'Mobility', sub: 'Stretch' },
  { name: 'Hamstring Stretch', cat: 'Mobility', sub: 'Stretch' },
  { name: 'Quad Stretch', cat: 'Mobility', sub: 'Stretch' },
  { name: 'IT Band Stretch', cat: 'Mobility', sub: 'Stretch' },
  { name: 'Full Body Stretch', cat: 'Mobility', sub: 'Stretch' },
  { name: 'Hip Mobility', cat: 'Mobility', sub: 'Mobility' },
  { name: 'Ankle Mobility', cat: 'Mobility', sub: 'Mobility' },
  { name: 'Shoulder Mobility', cat: 'Mobility', sub: 'Mobility' },
  { name: 'Thoracic Mobility', cat: 'Mobility', sub: 'Mobility' },
  { name: 'Cat Cow', cat: 'Mobility', sub: 'Mobility' },
  { name: "World's Greatest Stretch", cat: 'Mobility', sub: 'Mobility' },
  { name: 'Foam Rolling', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Massage Gun', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Ice Bath', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Sauna', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Walk', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Meditation', cat: 'Mobility', sub: 'Recovery' },
  { name: 'Glute Activation', cat: 'Mobility', sub: 'Prehab' },
  { name: 'Band Pull Aparts', cat: 'Mobility', sub: 'Prehab' },
  { name: 'Core Activation', cat: 'Mobility', sub: 'Prehab' },
]