// ─── PACE4 EXERCISE DATABASE ─────────────────────────────────────
// Edit this file to add, remove or update exercises
//
// fieldType options:
//   'strength'       → reps + weight (barbell/dumbbell exercises)
//   'reps_only'      → reps only (push ups, burpees, bodyweight)
//   'cardio_run'     → distance (km) + duration (min) + pace (min/km)
//   'cardio_machine' → distance (m) + duration (min) [rowing, skierg]
//   'cardio_cycle'   → distance (km) + duration (min) [cycling]
//   'timed'          → duration only [plank, yoga, stretching]
//   'sport'          → duration + notes [sparring, drills, practice]

export const ALL_EXERCISES = [
  { name: 'Flat Barbell Bench Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Incline Barbell Bench Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Decline Barbell Bench Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Smith Machine Bench Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Machine Chest Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Dumbbell Flat Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Incline Dumbbell Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Decline Dumbbell Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Kettlebell Floor Press', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Cable Chest Fly', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Incline Cable Fly', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Decline Cable Fly', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Pec Deck Machine', cat: 'Strength', sub: 'Chest', fieldType: 'strength' },
  { name: 'Push-Ups (Standard)', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Push-Ups (Incline)', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Push-Ups (Decline)', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Weighted Push-Ups', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Archer Push-Ups', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Clap Push-Ups', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Ring Push-Ups', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Ring Dips', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Parallel Bar Dips', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Weighted Dips', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Assisted Machine Dips', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Isometric Chest Squeeze', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Resistance Band Chest Press', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Resistance Band Fly', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Medicine Ball Push-Ups', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Suspension Trainer Chest Press', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Suspension Trainer Fly', cat: 'Strength', sub: 'Chest', fieldType: 'reps_only' },
  { name: 'Conventional Deadlift', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Sumo Deadlift', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Romanian Deadlift', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Stiff-Leg Deadlift', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Trap Bar Deadlift', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Rack Pulls', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Barbell Bent-Over Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Pendlay Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Yates Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Dumbbell Row (One Arm)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Dumbbell Row (Two Arm)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Chest-Supported Dumbbell Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Kettlebell Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'T-Bar Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Seated Cable Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Wide Grip Seated Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Close Grip Seated Row', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Lat Pulldown (Wide Grip)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Lat Pulldown (Close Grip)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Lat Pulldown (Neutral Grip)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Lat Pulldown (Reverse Grip)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Pull-Ups (Standard)', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Pull-Ups (Weighted)', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Pull-Ups (Neutral Grip)', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Pull-Ups (Wide Grip)', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Pull-Ups (Close Grip)', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Chin-Ups', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Assisted Machine Pull-Ups', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Inverted Row', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Suspension Trainer Row', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Face Pulls (Cable)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Resistance Band Rows', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Resistance Band Face Pulls', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Machine Row (Hammer Strength)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Machine Row (Iso-Lateral)', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Machine Assisted Row', cat: 'Strength', sub: 'Back', fieldType: 'reps_only' },
  { name: 'Good Mornings', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Reverse Hyperextensions', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Back Extensions', cat: 'Strength', sub: 'Back', fieldType: 'strength' },
  { name: 'Barbell Overhead Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Seated Barbell Overhead Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Standing Barbell Overhead Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Dumbbell Shoulder Press (Seated)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Dumbbell Shoulder Press (Standing)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Arnold Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Machine Shoulder Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Smith Machine Shoulder Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Kettlebell Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Push Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Military Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Lateral Raises (Dumbbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Lateral Raises (Cable)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Lateral Raises (Machine)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Front Raises (Dumbbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Front Raises (Plate)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Front Raises (Cable)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Rear Delt Fly (Dumbbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Rear Delt Fly (Cable)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Rear Delt Fly (Machine)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Shrugs (Barbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Shrugs (Dumbbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Shrugs (Smith Machine)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Shrugs (Trap Bar)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Upright Row (Barbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Upright Row (Dumbbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Upright Row (Cable)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Upright Row (Smith Machine)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Handstand Push-Ups', cat: 'Strength', sub: 'Shoulders', fieldType: 'reps_only' },
  { name: 'Pike Push-Ups', cat: 'Strength', sub: 'Shoulders', fieldType: 'reps_only' },
  { name: 'Resistance Band Shoulder Press', cat: 'Strength', sub: 'Shoulders', fieldType: 'reps_only' },
  { name: 'Resistance Band Lateral Raise', cat: 'Strength', sub: 'Shoulders', fieldType: 'reps_only' },
  { name: 'Resistance Band Front Raise', cat: 'Strength', sub: 'Shoulders', fieldType: 'reps_only' },
  { name: 'Overhead Plate Hold', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Z Press (Seated Barbell)', cat: 'Strength', sub: 'Shoulders', fieldType: 'strength' },
  { name: 'Barbell Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'EZ Bar Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Dumbbell Curl (Seated)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Dumbbell Curl (Standing)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Incline Dumbbell Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Hammer Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Reverse Curl (Barbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Reverse Curl (Dumbbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Preacher Curl (Barbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Preacher Curl (Dumbbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Cable Curl (Straight Bar)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Cable Curl (Rope)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Concentration Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Zottman Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Spider Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Tricep Pushdown (Rope)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Tricep Pushdown (Straight Bar)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Tricep Pushdown (V-Bar)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Overhead Tricep Extension (Dumbbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Overhead Tricep Extension (Barbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Overhead Tricep Extension (Cable)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Skull Crushers (EZ Bar)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Skull Crushers (Barbell)', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Dumbbell Skull Crushers', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Close Grip Bench Press', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Dips (Triceps Focus)', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Weighted Dips (Triceps)', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Assisted Machine Dips', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Kettlebell Curl', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Kettlebell Tricep Extension', cat: 'Strength', sub: 'Arms', fieldType: 'strength' },
  { name: 'Resistance Band Curl', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Resistance Band Tricep Extension', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Bodyweight Tricep Extension', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Isometric Bicep Hold', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Isometric Tricep Hold', cat: 'Strength', sub: 'Arms', fieldType: 'reps_only' },
  { name: 'Back Squat (Barbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Front Squat (Barbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Overhead Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Box Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Pause Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Hack Squat (Machine)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Smith Machine Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Goblet Squat (Dumbbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Kettlebell Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Pistol Squat', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Bulgarian Split Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Walking Lunges', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Stationary Lunges', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Reverse Lunges', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Side Lunges', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Curtsy Lunges', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Leg Press (Standard)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Leg Press (Single Leg)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Leg Extension (Machine)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Leg Curl (Machine)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Seated Leg Curl', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Standing Leg Curl', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Romanian Deadlift (Barbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Romanian Deadlift (Dumbbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Stiff-Leg Deadlift', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Glute Bridge', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Hip Thrust (Barbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Hip Thrust (Machine)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Step-Ups (Dumbbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Step-Ups (Barbell)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Calf Raises (Standing)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Calf Raises (Seated)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Calf Raises (Smith Machine)', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Donkey Calf Raises', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Sissy Squat', cat: 'Strength', sub: 'Legs', fieldType: 'strength' },
  { name: 'Wall Sit', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Resistance Band Squat', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Resistance Band Leg Press', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Resistance Band Glute Bridge', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Nordic Hamstring Curl', cat: 'Strength', sub: 'Legs', fieldType: 'reps_only' },
  { name: 'Power Clean', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Hang Clean', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Clean and Jerk', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Split Jerk', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Push Jerk', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Snatch', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Hang Snatch', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Power Snatch', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Push Press', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Thruster (Barbell)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Thruster (Dumbbell)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Thruster (Kettlebell)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Kettlebell Swing (Two-Hand)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Kettlebell Swing (One-Hand)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Kettlebell Snatch', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Kettlebell Clean and Press', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Turkish Get-Up', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Medicine Ball Slam', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Medicine Ball Throw (Overhead)', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Medicine Ball Chest Pass', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Sled Push', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Sled Pull', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Farmer’s Walk (Dumbbell)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Farmer’s Walk (Kettlebell)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Yoke Carry', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Sandbag Carry', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Log Press', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Atlas Stone Lift', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Muscle-Ups (Bar)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Muscle-Ups (Rings)', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Handstand Push-Ups', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Plyometric Push-Ups', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Broad Jumps', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Box Jumps (Weighted)', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Depth Jumps', cat: 'Strength', sub: 'Power', fieldType: 'strength' },
  { name: 'Clap Pull-Ups', cat: 'Strength', sub: 'Power', fieldType: 'reps_only' },
  { name: 'Easy Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Tempo Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Long Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Interval Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Hill Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Sprint Session', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Fartlek Training', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Recovery Jog', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Trail Run', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Track Intervals', cat: 'Conditioning', sub: 'Running', fieldType: 'cardio_run' },
  { name: 'Row Erg', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'SkiErg', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Assault Bike', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Stairmaster', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Elliptical', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Treadmill Run', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_run' },
  { name: 'Treadmill Incline Walk', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Spin Bike', cat: 'Conditioning', sub: 'Machine', fieldType: 'cardio_machine' },
  { name: 'Steady State Ride', cat: 'Conditioning', sub: 'Cycling', fieldType: 'cardio_cycle' },
  { name: 'Interval Ride', cat: 'Conditioning', sub: 'Cycling', fieldType: 'cardio_cycle' },
  { name: 'Indoor Cycling (Spin)', cat: 'Conditioning', sub: 'Cycling', fieldType: 'cardio_machine' },
  { name: 'Hill Climb Ride', cat: 'Conditioning', sub: 'Cycling', fieldType: 'cardio_cycle' },
  { name: 'Time Trial Ride', cat: 'Conditioning', sub: 'Cycling', fieldType: 'cardio_cycle' },
  { name: 'Burpees', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Box Jumps', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Jump Rope', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Battle Ropes', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Mountain Climbers', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Tabata Circuit', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'AMRAP Circuit', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'EMOM Circuit', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Jump Squats', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Lunge Jumps', cat: 'Conditioning', sub: 'HIIT', fieldType: 'reps_only' },
  { name: 'Plank', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Side Plank', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Hollow Hold', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'L-Sit', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Crunches', cat: 'Conditioning', sub: 'Core', fieldType: 'cardio_run' },
  { name: 'Bicycle Crunches', cat: 'Conditioning', sub: 'Core', fieldType: 'cardio_run' },
  { name: 'Leg Raises', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Hanging Leg Raises', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Ab Wheel Rollout', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Russian Twist', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Dragon Flag', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'V-Ups', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Dead Bug', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Weighted Plank', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Plank with Shoulder Tap', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Side Plank with Hip Dip', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Plank to Push-Up', cat: 'Conditioning', sub: 'Core', fieldType: 'timed' },
  { name: 'Stability Ball Rollout', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Stability Ball Pike', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Cable Woodchopper (Low to High)', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Cable Woodchopper (High to Low)', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Landmine Twist', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Landmine Press with Rotation', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Medicine Ball Russian Twist', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Medicine Ball Slam to Sit-Up', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Hanging Knee Raises', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Hanging Oblique Raises', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Windshield Wipers', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Dragon Flag Progression', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Weighted Sit-Ups', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Weighted V-Ups', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Ab Rollout (Barbell)', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Suspension Trainer Pike', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Suspension Trainer Knee Tuck', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Bird Dog', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Superman Hold', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Side-to-Side Medicine Ball Toss', cat: 'Conditioning', sub: 'Core', fieldType: 'reps_only' },
  { name: 'Sprint Intervals with Weighted Vest', cat: 'Conditioning', sub: 'Advanced', fieldType: 'cardio_run' },
  { name: 'Sled Push Intervals', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Sled Drag Intervals', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Battle Rope Waves with Burpees', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Kettlebell Complex (Swing + Clean + Press)', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Dumbbell Complex (Squat + Curl + Press)', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Barbell Complex (Deadlift + Row + Press)', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Sandbag Carry Intervals', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Farmer’s Carry Shuttle', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Medicine Ball Slam Intervals', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Medicine Ball Rotational Throws', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Plyometric Circuit (Box Jumps + Clap Push-Ups)', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Agility Ladder Drills', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Cone Shuttle Sprints', cat: 'Conditioning', sub: 'Advanced', fieldType: 'cardio_run' },
  { name: 'Burpee Pull-Ups', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Wall Ball Shots', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Row Erg Sprint Intervals', cat: 'Conditioning', sub: 'Advanced', fieldType: 'cardio_run' },
  { name: 'Assault Bike Tabata', cat: 'Conditioning', sub: 'Advanced', fieldType: 'cardio_machine' },
  { name: 'Stair Sprint Repeats', cat: 'Conditioning', sub: 'Advanced', fieldType: 'cardio_run' },
  { name: 'Weighted Jump Squats', cat: 'Conditioning', sub: 'Advanced', fieldType: 'reps_only' },
  { name: 'Football Passing Drills', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Football Dribbling Drills', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Football Shooting Practice', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Cricket Batting Nets', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Cricket Bowling Nets', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Basketball Shooting Drills', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Basketball Passing Drills', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Volleyball Serving Practice', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Volleyball Blocking Practice', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Scrimmage Match', cat: 'Skills', sub: 'Team Sports', fieldType: 'sport' },
  { name: 'Tennis Forehand Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Squash Forehand Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Tennis Backhand Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Squash Backhand Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Badminton Smash Practice', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Badminton Drop Shot Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Squash Rally Practice', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Table Tennis Serve Drill', cat: 'Skills', sub: 'Racket', fieldType: 'sport' },
  { name: 'Boxing Pad Work', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Boxing Heavy Bag', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Kickboxing Combo Drills', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Muay Thai Clinch Practice', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'MMA Sparring', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Brazilian Jiu-Jitsu Rolling', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Wrestling Takedown Drills', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Judo Throw Practice', cat: 'Skills', sub: 'Combat', fieldType: 'sport' },
  { name: 'Handstand Practice', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Cartwheel Drill', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Parkour Vaults', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Parkour Wall Runs', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Breakdancing Footwork', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Breakdancing Power Moves', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Climbing Bouldering Practice', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Climbing Rope Ascents', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Dance Choreography Drill', cat: 'Skills', sub: 'Movement', fieldType: 'sport' },
  { name: 'Freestyle Football Juggling', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Around the World Trick', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Crossover Trick', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Neck Stall', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Head Stall', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Foot Stall', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Freestyle Football Combos', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Backflip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Front Flip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Side Flip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Wall Flip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Gainer Flip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Cork Screw', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Aerial (No-Hand Cartwheel)', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Butterfly Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: '540 Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: '720 Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Hook Kick Twist', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Double Leg Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Flash Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Cartwheel Twist', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Roundoff Backflip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Roundoff Back Handspring', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Arabian Flip', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Tornado Kick', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'B-Twist (Butterfly Twist)', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Double Cork Screw', cat: 'Skills', sub: 'Freestyle Acrobatics', fieldType: 'sport' },
  { name: 'Roundoff Back Handspring', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Roundoff Backflip', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Roundoff Back Tuck', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Roundoff Back Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Roundoff Back Full Twist', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Front Handspring', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Front Tuck', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Front Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Front Full Twist', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Arabian Flip', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Double Backflip', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Double Front Flip', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Triple Backflip', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Whip Back', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Whip Back to Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Back Handspring to Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Back Handspring to Full Twist', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Front Handspring to Front Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Standing Back Tuck', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Standing Back Layout', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Standing Full Twist', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Planche Push-Up', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Handstand Press to Handstand', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Press to Planche', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Maltese Hold', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Iron Cross', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Inverted Cross', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Victorian Hold', cat: 'Skills', sub: 'Gymnastics Power', fieldType: 'sport' },
  { name: 'Straddle Planche', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Full Planche Push-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'One Arm Pull-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'One Arm Muscle-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: '360 Pull-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Bar Spin', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Front Lever Pull-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Back Lever Pull-Up', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Dragon Flag', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'L-Sit to Handstand', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'V-Sit Hold', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Manna Hold', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'One Arm Handstand', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Press to Handstand', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Freestyle Bar Flow Combo', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Dynamic Muscle-Up ', cat: 'Skills', sub: 'Calisthenics', fieldType: 'sport' },
  { name: 'Muscle-Up', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Human Flag', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Planche Hold', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Front Lever', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Back Lever', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Freestyle Bar Flow', cat: 'Skills', sub: 'Freestyle', fieldType: 'sport' },
  { name: 'Sun Salutation A', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Sun Salutation B', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Warrior Flow', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Balance Flow', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Power Vinyasa', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Restorative Flow', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Yin Yoga Sequence', cat: 'Mobility', sub: 'Yoga', fieldType: 'timed' },
  { name: 'Hamstring Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Quadriceps Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Hip Flexor Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Glute Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Shoulder Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Chest Opener Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Spinal Twist', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Calf Stretch', cat: 'Mobility', sub: 'Stretch', fieldType: 'timed' },
  { name: 'Hip Circles', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Shoulder Dislocates (Band)', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Thoracic Spine Rotations', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Ankle Mobility Drill', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: '90/90 Hip Switches', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Deep Squat Hold', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Cat-Cow Flow', cat: 'Mobility', sub: 'Drill', fieldType: 'timed' },
  { name: 'Foam Rolling Quads', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Foam Rolling Hamstrings', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Foam Rolling Back', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Lacrosse Ball Shoulder Release', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Lacrosse Ball Glute Release', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Percussion Gun Recovery', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Stretch Strap Assisted Recovery', cat: 'Mobility', sub: 'Recovery', fieldType: 'timed' },
  { name: 'Banded External Rotations', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Banded Internal Rotations', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Scapular Wall Slides', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Glute Activation Bridges', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Monster Walks (Band)', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Copenhagen Plank', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
  { name: 'Single-Leg Balance with Reach', cat: 'Mobility', sub: 'Prehab', fieldType: 'timed' },
]
